include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  
  errors:
    missing_required_param: error
    todo: ignore
    depend_on_referenced_packages: ignore
    use_build_context_synchronously: ignore


dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 3
    source-lines-of-code: 30
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    
linter:
  
  rules:
       
    
    
     - require_trailing_commas
     - slash_for_doc_comments
     - sort_child_properties_last
  

