name: verxr
description: verXR App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1-dev.3+3

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.15.2
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_auth_mocks: ^0.8.4
  firebase_core: ^1.19.1
  firebase_remote_config: ^2.0.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_keyboard_visibility: ^5.3.0
  flutter_svg: ^1.1.1+1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  iconify_flutter: ^0.0.4
  intl: ^0.17.0
  mockito: ^5.2.0
  regexed_validator: ^2.0.0+1
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
