name: verxr
description: verXR App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.15.2
  firebase_auth: ^3.3.19
  firebase_auth_mocks: ^0.8.4
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
