// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuR3HiPSWzDAU6LacEKEpFCO9DbfVkdp0',
    appId: '1:15091281628:android:9d014ab02430fc900d4e19',
    messagingSenderId: '15091281628',
    projectId: 'verxr-app-database',
    storageBucket: 'verxr-app-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsXgQsSQ0fksp6X_vgIwlGxLLL4k8Q2lg',
    appId: '1:15091281628:ios:ee054218ae5182410d4e19',
    messagingSenderId: '15091281628',
    projectId: 'verxr-app-database',
    storageBucket: 'verxr-app-database.appspot.com',
    androidClientId:
        '15091281628-7nuloj7c2tocfdcp1ojq3j6tor0h1g5i.apps.googleusercontent.com',
    iosClientId:
        '15091281628-atj6h35cb6oc8krcfufq86oioulbkaok.apps.googleusercontent.com',
    iosBundleId: 'verxr.app',
  );
}
